yer_yon_belirten = [
    "üst",
    "alt",
    "solunda",
    "sağında",
    "yanı",
    "civar",
    "yakın",
    "altında",
    "arka",
    "önü",
    "çapraz",
    "çarpraz",
    "karşı",
    "yan taraf",
    "taraf",
    "yapıt",
    "yapıları",
    "kooperatif",
    "bina",
    "merkez",
    "bölge",
    "alanı",
    "pazarı",
    "orta",
    "ara",
    "kuzey",
    "güney",
    "doğu",
    "batı",
    "ötesi",
    "üstü",
    "ilk ",
    "son ",
    "ikinci",
    "üçüncü",
    "dördüncü",
    "bitişi",
    "yol",
    "tepesi",
    "köy",
    "kent",
    "rezidans",
    "residans",
    "residanz",
    "rezidanz",
    "otel",
    "hotel",
    "motel",
    "pansiyon",
    "yurt",
    "mevki",
    "konutları",
    "konutu",
    "blok",
    "apartman",
    "komplex",
    "kompleks",
    "geçit",
    "geçidi",
    "köprü",
    "Residence",
    "Kat",
    "evleri",
    "evler",
    "sehir",
    "city",
    "konak",
    "konağı",
    "lojman",
    "köşe",
    "tesis",
    "dış kapı",
    "meydan",
    "okul",
    "mıntıka",
    "mezra",
    "biraz ileri",
    "az ileri",
    "üzeri",
    "plaza",
    "pilaza",
    "bakkal",
    "market",
    "avm",
    "cami",
    "muhtar",
    "valili",
    "orası",
    "apart",
    "ocak",
    "sağlık ocağı",
    "banka",
    "No:",
    "Numara",
    "park",
    "işletme",
    "yazane",
    "yazhane",
    "yazıhane",
    "mesire",
    "karakol",
    "orada",
    "çevre",
    "kavşa",
    "residance",
    "hizası",
    "kışla",
    "göbe",
    "kasaba",
    "kösebasi",
    "basi",
    "hayvancilik",
    "stad",
    "stadyum",
    "salon",
    "cevreyolu",
    "semt",
    "köy evi",
    "köyevi",
    "çıkmazı",
    "eczane",
    "inşaat",
    "polis evi",
    "polisevi",
    "mağaza",
    "tower",
    "kule",
    "vilayet",
    "koop",
    "hospital",
    "ahır",
    "petrol",
    "ofis",
    "yurdu",
    "çamlık",
    "çarpaz",
    "girişi",
    "askeriye",
    "akademi",
    "fabrika",
    "kurum",
    "müdürlü",
    "lise",
    "üniversite",
    "kampüs",
    "komutan",
    "bölük",
    "bölüğü",
    "kısım",
    "bölüm",
    "gerisi",
    "bılok",
    "blog",
    "şantiye",
    "kaymakam",
    "vakıf",
    "dernek",
    "derneği",
    "vakfı",
    "bayi",
    "mobilya",
    "ticaret",
    "yapı",
    "otomobil",
    "oto.",
    "belediye",
    "bahçe",
    "avlu",
    "trafik",
    "ışıklar",
    "yokuş",
    "müstakil",
    "kuruyemiş",
    "kolej",
    "kollej",
    "tekel",
    "manav",
    "kasap",
    "muhit",
    "muhid",
    "lokanta",
    "pide",
    "restoran",
    "galeri",
    "lastik",
    "benzinlik",
    "cafe",
    "kafe",
    "kahve",
    "kıraathane",
    "kırathane",
    "kıratane",
    "kıraatane",
    "kağve",
    "emniyet",
    "çevik kuvvet",
    "toki",
    "otopark",
    "bayır",
    "hisar",
    "fakülte",
    "prefabrik",
    "sk",
    "sokak",
    "sok",
    "sokağı",
    "sokak:",
    "sokak :",
    "sk.",
    "sk.:",
    "sk. :",
    "sok.",
    "sok.:",
    "sok. :",
    "cadde:",
    "cadde",
    "cd",
    "cd.",
    "cd.:",
    "cd. :",
    "cad",
    "cad.",
    "cad.:",
    "cad. :",
    "apartmani",
    "apartmanı",
    "apt.",
    "apt",
    "mahalle:",
    "mahalle",
    "mahalle :",
    "mh",
    "mh.",
    "mh.:",
    "mh. :",
    "mah",
    "mah.",
    "mah. :",
    "mah.:",
    "mahallesi",
    "mahallesi:",
    "mahallesi :",
    "mhl",
    "mhl.",
    "mhl.:",
    "mhl. :",
    "mahll",
    "mahll.",
    "mahll.:",
    "mahll. :",
    "Aoartmanı",
    "Aoartnamı",
    "Aoatrmamı",
    "Apatrmamı",
    "Apatrnanı",
    "Apartnanı",
    "sitesi",
    "site",
    "üstünde",
    "altındaki",
    "solunda ki",
    "sağında ki",
    "yanında",
    "çevresi",
    "yakınında",
    "arka tarafı",
    "ön tarafı",
    "çaprazındaki",
    "karşısında",
    "yan taraflar",
    "yapım",
    "kooperatifler",
    "binalar",
    "merkezi",
    "bölgeler",
    "alanları",
    "pazar yeri",
    "arası",
    "kuzeyi",
    "güneyi",
    "doğusu",
    "batısı",
    "üst tarafı",
    "ilk sıra",
    "son sıra",
    "ikinci sıra",
    "üçüncü sıra",
    "dördüncü sıra",
    "bitiş noktası",
    "yolu",
    "köyü",
    "kenti",
    "rezidanslar",
    "oteller",
    "pansiyonlar",
    "yurtlar",
    "mevkii",
    "konut kompleksleri",
    "apartman blokları",
    "köprüsü",
    "kattaki",
    "şehir merkezi",
    "konakları",
    "lojmanlar",
    "köşedeki",
    "tesisleri",
    "dış kapısı",
    "meydanı",
    "okulu",
    "mıntıkası",
    "mezraları",
    "biraz ilerisi",
    "az ilerisi",
    "üstünde ki",
    "plazası",
    "bakkallar",
    "marketler",
    "camisi",
    "muhtarlık",
    "valilik",
    "ocakları",
    "bankası",
    "numarası",
    "parkı",
    "işletmesi",
    "yazıhanesi",
    "mesire yeri",
    "karakolu",
    "kavşağı",
    "residansı",
    "hizasında",
    "kışlası",
    "göbeği",
    "kasabası",
    "köşebaşı",
    "hayvancılık",
    "stadyumu",
    "salonu",
    "çevre yolu",
    "semti",
    "köy evleri",
    "eczanesi",
    "inşaatı",
    "polis evleri",
    "mağazası",
    "kulesi",
    "vilayeti",
    "kooperatifi",
    "hastanesi",
    "ahırı",
    "petrol istasyonu",
    "ofisi",
    "çamlığı",
    "çarpazı",
    "girişleri",
    "askeriyeler",
    "akademisi",
    "fabrikası",
    "kurumu",
    "müdürlüğü",
    "lisesi",
    "üniversitesi",
    "kampüsü",
    "komutanlık",
    "kısmı",
    "bölümü",
    "blokları",
    "blogu",
    "şantiyesi",
    "kaymakamlık",
    "vakıfları",
    "dernekleri",
    "bayiler",
    "mobilya mağazaları",
    "ticaret merkezleri",
    "otomobiller",
    "bankalar",
    "belediyesi",
    "bahçesi",
    "avlusu",
    "trafik ışıkl",
    "yanındaki",
    "yanı başındaki",
    "kuzeybatı",
    "kuzeydoğu",
    "güneybatı",
    "güneydoğu",
    "ortasında",
    "yan taraftaki",
    "yapıtları",
    "merkezler",
    "alanlar",
    "pazarlar",
    "aralık",
    "kuzey yönü",
    "güney yönü",
    "doğu yönü",
    "batı yönü",
    "otelin",
    "evlerin",
    "köşk",
    "tesislerin",
    "dış kapısının",
    "okulun",
    "ortam",
    "meydanın",
    "biraz ilerisindeki",
    "plaza'nın",
    "camiler",
    "apartmanın",
    "sağlık ocağının",
    "bankanın",
    "parkın",
    "işletmenin",
    "kışla'nın",
    "kasaba'nın",
    "stadyumun",
    "salonun",
    "köy evlerinin",
    "eczanenin",
    "inşaatın",
    "polis evinin",
    "mağazanın",
    "tower'ın",
    "kooperatifin",
    "hastanenin",
    "ahırın",
    "ofisin",
    "yurdun",
    "çamlığın",
    "askeriyenin",
    "kurumun",
    "müdürlük",
    "lisenin",
    "üniversitenin",
    "kampüsün",
    "komutanın",
    "bölüğün",
    "bölümün",
    "blokların",
    "şantiyenin",
    "vakfın",
    "derneğin",
    "bayinin",
    "mobilyacı",
    "yapıların",
    "oto tamircisi",
    "belediye binası",
    "bahçenin",
    "avlunun",
    "trafik ışıkları",
    "yokuşun",
    "müstakil ev",
    "kuruyemişçi",
    "tekel bayisi",
    "manavın",
    "kasabın",
    "lokantanın",
    "restoranın",
    "galerinin",
    "lastikçinin",
    "benzinliğin",
    "cafenin",
    "kahveci",
    "kıraathanenin",
    "emniyetin",
    "çevik kuvvetin",
    "TOKİ'nin",
    "otoparkın",
    "hisarın",
    "fakültenin",
    "prefabrik evlerin",
    "sokakların",
    "caddelerin",
    "mahallelerin",
    "no",
    "berber",
    "kuafor",
    "kiosk",
    "hane",
    "kapı",
    "tesisat",
    "çiftlik",
    "hangar",
    "yaya geçidi",
    "tren istasyonu",
    "havalimanı",
    "park alanı",
    "kamp alanı",
    "balıkçı barınağı",
    "teknopark",
    "sınır",
    "sahil",
    "otobüs durağı",
    "bisiklet parkuru",
    "depo",
    "konsey binası",
    "mescit",
    "gölet",
    "halı saha",
    "sosyal tesis",
    "bölge parkı",
    "bilim merkezi",
    "kültür merkezi",
    "çim saha",
    "sergi salonu",
    "botanik bahçesi",
    "opera binası",
    "kongre merkezi",
    "sinema",
    "tiyatro",
    "mezarlık",
    "su kulesi",
    "ateş kulesi",
    "liman",
    "marina",
    "mavi yolculuk iskelesi",
    "su sporları merkezi",
    "çay bahçesi",
    "kır kahvesi",
    "tarihi mekan",
    "turistik mekan",
    "kültürel miras",
    "şelale",
    "ulusal park",
    "yaban hayatı koruma alanı",
    "doğal sit alanı",
    "yeraltı şehri",
    "antik kent",
    "kervansaray",
    "katedral",
    "kilise",
    "camii",
    "sinagog",
    "müze",
    "turistik tren",
    "ziyaret yeri",
    "kültürel kompleks",
    "yazlık",
    "kışlık",
    "su kaynağı",
    "termal tesis",
    "yel değirmeni",
    "tarım arazisi",
    "hayvanat bahçesi",
    "aquapark",
    "adliye",
    "askeri üs",
    "devlet daireleri",
    "aile sağlığı merkezi",
    "çocuk parkı",
    "yürüyüş parkuru",
    "bisiklet yolu",
    "ormanlık alan",
    "akvaryum",
    "bowling salonu",
    "buz pateni pisti",
    "paintball alanı",
    "dart salonu",
    "kafeterya",
    "pastane",
    "köpek parkı",
    "konser salonu",
    "at yarışı pisti",
    "golf sahası",
    "kayak merkezi",
    "buz hokeyi sahası",
    "otomatik yıkama merkezi",
    "öğrenci yurdu",
    "baraj",
    "meteoroloji istasyonu",
    "askeri lojman",
    "sanayi bölgesi",
    "lojistik merkez",
    "nakliye merkezi",
    "çadır kampı",
    "su arıtma tesisi",
    "elektrik santrali",
    "hidroelektrik santral",
    "biyolojik arıtma tesisi",
    "maden ocağı",
    "maden arama sahası",
    "tünel",
    "teleferik",
    "asansör",
    "tarihi hamam",
    "tarihi köprü",
    "tarihi çarşı",
    "tarihi kervansaray",
    "çocuk yuvası",
    "gençlik merkezi"
]

ifadeler = [
    "yiyecek ve barinma ihtiyaci var!",
    "yiyecek ihtiyaci var!",
    "yiyecek ihtiyaci var",
    "yiyecek be barinma ihtiyaci var",
    "yikimdan beri",
    "yikimdan",
    "yedi kisilermis!",
    "yedi kisilermis",
    "yedi kisi",
    "yedi kadin",
    "yedi erkek",
    "yaslilar varmis!",
    "yaslilar varmis",
    "yaslilar var!",
    "yaslilar var",
    "yasli varmis!",
    "yasli varmis",
    "yasli var!",
    "yasli var",
    "yasli kadinlar varmis!",
    "yasli kadinlar varmis",
    "yasli kadinlar var!",
    "yasli kadinlar var",
    "yasli kadin varmis!",
    "yasli kadin varmis",
    "yasli kadin var!",
    "yasli kadin var",
    "YASLI HASTA",
    "yasli adamlar varmis!",
    "yasli adamlar varmis",
    "yasli adamlar var!",
    "yasli adamlar var!",
    "yasli adamlar var",
    "yasli adamlar var",
    "yasli adam varmis!",
    "yasli adam varmis",
    "yasli adam var!",
    "yasli adam var",
    "yasiyormus!",
    "yasiyormus",
    "yasayanlar",
    "yasayan",
    "yasam belirtisi varmis!",
    "yasam belirtisi varmis",
    "yasam belirtisi var!",
    "yasam belirtisi var",
    "yasadiklari teyit edilmis!",
    "yasadiklari teyit edilmis",
    "yasadigi teyit edilmis!",
    "yasadigi teyit edilmis",
    "yarim yok",
    "yardım talebi - kırmızı ",
    "yardım lutfen",
    "yardım gerekli",
    "yardım cagrısı - kırmızı",
    "yardima gelen yok",
    "yardim gonderin!",
    "yardim gonderin",
    "yardim gitmiyormus!",
    "yardim gitmiyormus",
    "yardim gitmiyor!",
    "yardim gitmiyor",
    "yardim gerekli!",
    "yardim gerekli!",
    "yardim gerekli",
    "yardim gerekiyormus!",
    "yardim gerekiyormus",
    "yardim gerekiyor!",
    "yardim gerekiyor",
    "yardim etmemis",
    "yardim ekibi lazimmis!",
    "yardim ekibi lazimmis",
    "yardim ekibi lazim!",
    "yardim ekibi lazim",
    "yardim bekliyormus!",
    "yardim bekliyormus",
    "yardim bekliyorlarmis!",
    "yardim bekliyorlarmis!",
    "yardim bekliyorlarmis!",
    "yardim bekliyorlarmis!",
    "yardim bekliyorlar!",
    "yardim bekliyorlar!",
    "yardim bekliyorlar",
    "yardim bekliyorlar",
    "yan yatmis!",
    "yan yatmis",
    "yaklasik",
    "yakit yok",
    "whatsapp",
    "vinc lazım",
    "vinc gerekli",
    "uzun suredir!",
    "uzun suredir",
    "ustuste devrilmis!",
    "ustuste devrilmis",
    "ulasmamis!",
    "ulasmamis",
    "ulasilamiyormus!",
    "ulasilamiyormus!",
    "ulasilamiyormus",
    "ulasilamiyormus",
    "ulasilamiyor!",
    "ulasilamiyor!",
    "ulasilamiyor",
    "ulasilamiyor",
    "ulasamiyoruz!",
    "ulasamiyoruz",
    "uc kisilermis!",
    "uc kisilermis",
    "uc kisi",
    "üc kadin ",
    "üc erkek",
    "twitter",
    "twiter",
    "tum ailesi!",
    "tum ailesi varmis!",
    "tum ailesi varmis",
    "tum ailesi var!",
    "tum ailesi var",
    "tum ailesi",
    "tum aile!",
    "tum aile var!",
    "tum aile var",
    "tum aile",
    "tıbbi destek gerekli!",
    "teyit edilmis!",
    "teyit edilmis",
    "tamamen yilkilmis!",
    "tamamen yilkilmis!",
    "tamamen yikilmis",
    "tamamen yikilmis",
    "tam yikilmamis!",
    "tam yikilmamis",
    "suredir!",
    "su yok",
    "soyleniyor!",
    "soyleniyor",
    "site yikilmis!",
    "site yikilmis",
    "site yikildi!",
    "site yikildi",
    "sesleri geliyor",
    "sesler var",
    "sesler geliyormus!",
    "sesler geliyormus",
    "sesler geliyor",
    "sesini duyuyuoruz!",
    "sesini duyuyoruz",
    "sesini duymuslar!",
    "sesini duymuslar",
    "sesini duyduk!",
    "sesini duyduk",
    "ses veriyorlar",
    "ses veriyor",
    "ses var",
    "ses geliyor",
    "sekiz kisilermis!",
    "sekiz kisilermis",
    "sekiz kisi",
    "sekiz kadin",
    "sekiz erkek",
    "on kisilermis!",
    "on kisilermis",
    "on kisi",
    "on kadin",
    "on dokuz",
    "olmek uzereler!",
    "olmek uzere!",
    "olmek uzere",
    "olecekler!",
    "olecekler",
    "oldugunu ogrendim!",
    "oldugunu ogrendim",
    "oldugu soyleniyor!",
    "oldugu soyleniyor!",
    "oldugu soyleniyor",
    "oldugu soyleniyor",
    "olanlar var!",
    "olanlar var",
    "ogrendim!",
    "ogrendim!",
    "ogrendim",
    "ogrendim",
    "nolur yardim edin!",
    "nolur yardim edin",
    "nolur",
    "nefes almakta gucluk cekiyormus!",
    "nefes almakta gucluk cekiyormus",
    "nefes aldiklari teyit edilmis!",
    "nefes aldiklari teyit edilmis",
    "nefes aldigi teyit edilmis!",
    "nefes aldigi teyit edilmis",
    "nefes alamiyormus!",
    "nefes alamiyormus",
    "ne olur!",
    "ne olur yardim edin!",
    "ne olur yardim edin",
    "ne olur",
    "ne olur",
    "mudahale edilmeli!",
    "mudahale edilmeli!",
    "mudahale edilmeli",
    "mudahale edilmeli",
    "mama lazimmis!",
    "mama lazimmis",
    "mama lazim!",
    "mama lazim",
    "mama gerekliymis",
    "mama gerekli!",
    "mama gerekli",
    "mama gerekiymis!",
    "malzemeleri yetmiyor!",
    "malzemeler yetersizmis!",
    "malzemeler yetersizdir!",
    "malzemeler yetersiz!",
    "makinesi lazimmis!",
    "makinesi lazimmis!",
    "makinesi lazim!",
    "makinesi lazim!",
    "makinesi lazim",
    "makinesi lazim",
    "makine lazim!",
    "makine lazim",
    "makinasi lazimmis!",
    "makinasi lazimmis!",
    "makinasi lazim!",
    "makinasi lazim!",
    "makinasi lazim",
    "makinasi lazim",
    "makina lazimmis!",
    "makina lazimmis!",
    "makina lazim!",
    "makina lazim",
    "lütfen!",
    "lütfen yardim edin!",
    "lütfen yardim edin",
    "lütfen cok gec olmadan!",
    "lütfen cok gec olmadan yarim edin!",
    "lütfen cok gec olmadan yarim edin",
    "lütfen cok gec olmadan",
    "lakin ulasilamiyor!",
    "lakin ulasilamiyor",
    "lakin ulasasilamiyormus!",
    "lakin ulasasilamiyormus",
    "kurtarimayi bekliyorlarmis!",
    "kurtarimayi bekliyorlarmis",
    "kurtarilmayi bekliyormus!",
    "kurtarilmayi bekliyormus",
    "kurtarilmayi bekliyorlar!",
    "kurtarilmayi bekliyor!",
    "kucuk cocuklar var!",
    "kucuk cocuklar var",
    "konustum!",
    "konustum",
    "komple yikilmis",
    "komple yikilmamis!",
    "komple yikilmamis",
    "Kıyafet (hasta yaşlı kadın)",
    "kırmızı - yardım cagrısı",
    "kırmızı - yardim talebi",
    "kırmızı - eksik bilgi",
    "kiyafet gerekiyor!",
    "kiyafet gerekiyor",
    "kisilermis!",
    "kisiden haber alinamiyor!",
    "kisiden haber alinamiyor",
    "kişi var",
    "kendisine ulasilamiyormus!",
    "kendisine ulasilamiyormus!",
    "kendisine ulasilamiyor!",
    "kendisine ulasilamiyor",
    "kendisinden haber alinamiyor!",
    "kendisinden haber alinamiyor",
    "kendi imkanlarıyla",
    "kendi imkanlari ile",
    "kardesi var!",
    "kaliyoruz",
    "kaliyorlar",
    "kalan bir aile!",
    "kalan bir aile",
    "iyiymis!",
    "iyiymis",
    "ismi bilinmiyor",
    "is makinesi lazim!",
    "is makinesi lazim",
    "is makinasi lazim!",
    "is makinasi lazim",
    "instagram",
    "ilk depremden sonra",
    "ilk depremden beri",
    "ile birlikte",
    "iki kisilermis!",
    "iki kisilermis",
    "iki kisi",
    "iki kadin",
    "iki gundur",
    "iki erkek",
    "ihtiyaclari varmis!",
    "ihtiyaclari varmis",
    "ihtiyaclari var!",
    "ihtiyaclari var",
    "ihtiyaci varmis",
    "ihtiyaci var!",
    "ihtiyaci var!",
    "ihtiyaci var",
    "ihtiyaci var",
    "hissetmiyormus!",
    "hissetmiyormus",
    "hissetmiyor!",
    "hissetmiyor",
    "hatırlamıyorum",
    "Hasta bezi xl",
    "halen ses veriyorlar",
    "halen ses veriyor",
    "halen ses geliyor",
    "halen gocuk altindaymis!",
    "halen gocuk altindaymis",
    "halen gocuk altindalarmis!",
    "halen gocuk altindalarmis",
    "halen gocuk altindalar!",
    "halen gocuk altindalar!",
    "halen gocuk altinda!",
    "halen gocuk altinda",
    "halen enkaz altindaymis!",
    "halen enkaz altindaymis",
    "halen enkaz altindalarmis!",
    "halen enkaz altindalarmis",
    "halen enkaz altindalar!",
    "halen enkaz altindalar!",
    "halen enkaz altinda!",
    "halen enkaz altinda",
    "hala yasiyorlar!",
    "hala yasiyorlar",
    "hala ses veriyor",
    "hala ses var",
    "hala ses veriyorlar",
    "hala ses geliyor",
    "haftadir",
    "haber alinamıyor",
    "gorulmus!",
    "gorulmus",
    "gocuk altındaymis",
    "gocuk altındalarmis!",
    "gocuk altında!",
    "gocuk altindaymis!",
    "gocuk altindalarmis!",
    "gocuk altindalarmis",
    "gocuk altindalar!",
    "gocuk altinda!",
    "gocuk altinda kalmislar!",
    "gocuk altinda kalmislar",
    "gocuk altinda kaldilar!",
    "gocuk altinda kaldilar",
    "gocuk altinda",
    "gibi malzemelere ihtiyac varmis",
    "gibi malzemelere ihtiyac var",
    "gibi malzemelere ihtiyac",
    "gibi malzemelere",
    "gerekiyormus!",
    "gerekiyormus",
    "geliyormus!",
    "geliyormus",
    "fazla var!",
    "fazla var",
    "fazla suredir!",
    "fazla suredir",
    "fakat ulasilamiyor!",
    "fakat ulasilamiyor",
    "fakat ulasasilamiyormus!",
    "fakat ulasasilamiyormus",
    "evleri yikilmis!",
    "evleri yikilmis!",
    "evleri yikilmis",
    "evleri yikilmis",
    "evden ses geldigi soyleniyor!",
    "evden ses geldigi soyleniyor!",
    "evden ses geldigi soyleniyor",
    "evden ses geldigi soyleniyor",
    "ev yikilmis!",
    "ev yikilmis!",
    "ev yikilmis",
    "ev yikilmis",
    "ev yikildi!",
    "ev yikildi",
    "ev tamamen yikilmis!",
    "ev tamamen yikilmis!",
    "ev tamamen yikilmis",
    "ev tamamen yikilmis",
    "erzak yardimi gerekiyor!",
    "erzak yardimi",
    "erzak yardim gerekiyor",
    "enkazdan",
    "enkazdan",
    "enkazda kalan",
    "enkazda bekleyen",
    "enkazda",
    "enkaz altındaymis",
    "enkaz altında kalmış",
    "enkaz altında kalan",
    "enkaz altında bekleyen",
    "enkaz altindaymis!",
    "enkaz altindalarmis!",
    "enkaz altindalarmis",
    "enkaz altinda kalmislar!",
    "enkaz altinda kalmislar",
    "enkaz altinda kaldilar!",
    "enkaz altinda kaldilar",
    "enkaz altinda",
    "eksik bilgi - kırmızı",
    "ekmek yok",
    "ekip yok!",
    "ekip yok",
    "ekip lazim!",
    "ekip lazim",
    "ekibi lazimmis!",
    "ekibi lazimmis",
    "ekibi lazim!",
    "ekibi lazim",
    "durumları kritikmis!",
    "durumları kritikmis!",
    "durumları kritikmis!",
    "durumları kritikmis!",
    "durumları kritik!",
    "durumları kritik!",
    "durumları kritik",
    "durumları kritik",
    "dort kisilermis!",
    "dort kisilermis",
    "dort kisi",
    "dört kadin ",
    "dort gundur",
    "dört erkek",
    "donmak uzereler!",
    "donmak uzere!",
    "donmak uzere",
    "donarak olmus!",
    "donarak olmus",
    "donarak olmek uzere!",
    "donarak olmak uzere",
    "dokuz kisilermis!",
    "dokuz kisilermis",
    "dokuz kisi",
    "dokuz kadin",
    "dokuz erkek",
    "destek lazim!",
    "destek lazim!",
    "destek lazim",
    "destek lazim",
    "destek gerekli!",
    "destek gerekli",
    "depremin ilk gununden beri",
    "depremden beri",
    "depremden",
    "deprem bölgesinde olan",
    "dayısı var",
    "dayısı",
    "dayıları var!",
    "dayıları var!",
    "daireden ses geldigi soyleniyor!",
    "daireden ses geldigi soyleniyor!",
    "daireden ses geldigi soyleniyor",
    "daireden ses geldigi soyleniyor",
    "daire tamamen yikilmis!",
    "daire tamamen yikilmis!",
    "daire tamamen yikilmis",
    "daire tamamen yikilmis",
    "daire komple yikilmis!",
    "daire komple yikilmis",
    "daire komple yikilmis",
    "daire komple yikilmis",
    "cok sayida kisi!",
    "cok sayida kisi!",
    "cok insan bekliyormus!",
    "cok insan bekliyormus",
    "cok insan bekliyor!",
    "cok insan bekliyor",
    "cok gec olmadan!",
    "cok gec olmadan yarim edin!",
    "cok gec olmadan yarim edin",
    "cok gec olmadan",
    "cok fazla var!",
    "cok fazla var",
    "cok acil!",
    "cocuklar var!",
    "cocuklar var",
    "çocuk sesleri geliyor",
    "çocuk sesi geliyor",
    "ciglikliklar duyduk!",
    "cigliklar duyuluyormus!",
    "cigliklar duyuluyormus",
    "cigliklar duyuluyor!",
    "cigliklar duyuluyor",
    "cigliklar duyduk",
    "cc gundur",
    "CANLI ACİL EKİP YARDIMI ",
    "calisiyorlarmis!",
    "calisiyorlarmis!",
    "calisiyorlar!",
    "calisiyorlar",
    "caidr lazim",
    "cadirlar lazimmis!",
    "cadirlar lazimmis",
    "cadirlar lazim!",
    "cadirlar lazim",
    "cadirlar gerekliymis!",
    "cadirlar gerekliymis",
    "cadirlar gerekli!",
    "cadirlar gerekli",
    "cadirlar gerekiyormus!",
    "cadirlar gerekiyormus",
    "cadirlar gerekiyor!",
    "cadirlar gerekiyor",
    "cadir lazimmis!",
    "cadir lazimmis",
    "cadir lazim!",
    "cadir gerekliymis!",
    "cadir gerekliymis",
    "cadir gerekli!",
    "cadir gerekli",
    "cadir gerekiyormus!",
    "cadir gerekiyormus",
    "cadir gerekiyor!",
    "cadir gerekiyor",
    "bolgeyi",
    "bolgeye gitmedi!",
    "bolgeye gitmedi",
    "bolgeye",
    "bolgenin",
    "bölgeden ses geldigi soyleniyor!",
    "bölgeden ses geldigi soyleniyor!",
    "bölgeden ses geldigi soyleniyor",
    "bölgeden ses geldigi soyleniyor",
    "bolgeden",
    "bolgede",
    "bir suredir!",
    "bir kisi",
    "bir kadin",
    "bir erkek",
    "bina yikilmis!",
    "bina yikilmis!",
    "bina yikilmis",
    "bina yikilmis",
    "bina yikildi!",
    "bina yikildi",
    "bina komple yikilmis!",
    "bina komple yikilmis",
    "bina komple yikilmis",
    "bina komple yikilmis",
    "bilmiyorum",
    "bilinmiyor",
    "bilgi yok",
    "bes kisilermis!",
    "bes kisilermis",
    "bes kisi",
    "bes kadin",
    "bes gundur",
    "bes erkek",
    "belirtisi varmis!",
    "belirtisi varmis",
    "belirtisi var!",
    "belirtisi var",
    "bebekler varmis!",
    "bebekler varmis",
    "bebekler var!",
    "bebekler var",
    "bebek varmis!",
    "bebek varmis",
    "bebek var!",
    "bebek var",
    "bebek var",
    "battaniye",
    "barinma ve yiyecek ihtiyaci var!",
    "barinma ve yiyecek ihtiyaci var",
    "barinma ihtiyaci var!",
    "barinma ihtiyaci var",
    "babasi!",
    "babasi",
    "az önce konustum!",
    "az önce konustum",
    "az önce konusmus!",
    "az önce konusmus",
    "az önce aramis!",
    "az önce aramis",
    "az önce aradi!",
    "az önce aradi",
    "ayni evdelermis",
    "ayni evdeler",
    "ayni dairedelermis",
    "ayni dairedeler",
    "ayni bolgedermis",
    "ayni bolgedermis",
    "apartmandan ses geldigi soyleniyor!",
    "apartmandan ses geldigi soyleniyor!",
    "apartmandan ses geldigi soyleniyor",
    "apartmandan ses geldigi soyleniyor",
    "apartman yıkıldi",
    "apartman yilkildi!",
    "apartman yikilmis!",
    "apartman yikilmis",
    "apartman tamamen yikilmis!",
    "apartman tamamen yikilmis!",
    "apartman tamamen yikilmis",
    "apartman tamamen yikilmis",
    "apartman komple yikilmis!",
    "apartman komple yikilmis",
    "apartman komple yikilmis",
    "apartman komple yikilmis",
    "annesi!",
    "annesi var!",
    "annesi",
    "anneannesi var!",
    "anneannesi var",
    "ancak",
    "amcası var!",
    "amcası",
    "ama ulasilamiyor!",
    "ama ulasilamiyor",
    "ama ulasasilamiyormus!",
    "ama ulasasilamiyormus",
    "ama ekip yok!",
    "ama ekip yok",
    "alti kisilermis!",
    "alti kisilermis",
    "alti kisi",
    "alti kadin",
    "alti gundur",
    "alti erkek",
    "aileye ulasilamiyormus!",
    "aileye ulasilamiyormus",
    "aileye ulasilamiyor!",
    "aileye ulasilamiyor",
    "ailesinden haber alinamiyor!",
    "ailesinden haber alinamiyor",
    "ailesi var!",
    "ailesi ile birlikte",
    "aile var!",
    "adı bilinmiyor",
    "açlık ve susuzluk",
    "aclar",
    "acil!",
    "acil yardim!",
    "acil yardim",
    "acil vinc lazımmis!",
    "acil vinc lazım",
    "acil makinesi lazimmis!",
    "acil makinesi lazimmis!",
    "acil makinesi lazimmis",
    "acil makinesi lazim!",
    "acil makinesi lazim",
    "acil makinasi lazimmis!",
    "acil makinasi lazimmis!",
    "acil makinasi lazim!",
    "acil makinasi lazim",
    "acil is makinesi lazimmis!",
    "acil is makinesi lazimmis!",
    "acil is makinesi lazim!",
    "acil is makinesi lazim",
    "acil is makinasi lazimmis!",
    "acil is makinasi lazimmis",
    "acil is makinasi lazim!",
    "acil is makinasi lazim",
    "acil ihtiyac!",
    "acil ihtiyac",
    "acil destek lazim!",
    "acil destek lazim",
    "acil destek",
    "ac ve susuzlar",
    "ac susuz",
    "4 erkek, 1 kadin",
    "4 erkek 1 kadin",
    "3 kadin, 3 erkek",
    "3 kadin 3 erkek",
    "3 erkek, 1 kadin",
    "3 erkek 3 kadin",
    "2 kadin 2 erkek",
    "2 erkek, 2 kadin",
    "1 kadin, 3 erkek",
    "1 kadin 2 erkek",
    "1 erkek, 4 kadin",
    "1 erkek 2 kadin",
    "adres tanımı"
]
